# Generated by Django 5.2 on 2025-05-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, help_text='Сделать профиль закрытым')),
                ('allow_comments', models.BooleanField(default=True, help_text='Разрешить комментарии к постам')),
                ('notify_likes', models.BooleanField(default=True, help_text='Уведомления о лайках')),
                ('notify_comments', models.BooleanField(default=True, help_text='Уведомления о комментариях')),
                ('notify_follows', models.BooleanField(default=True, help_text='Уведомления о подписках')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
