# Generated by Django 5.2 on 2025-05-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_date_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
